name: Release Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  release-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Current Tag
        id: tag
        uses: "WyriHaximus/github-action-get-previous-tag@master"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            fobhep/iperf3-speedtest-exporter:latest
            fobhep/iperf3-speedtest-exporter:${{ steps.tag.outputs.tag }}
